spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/huoyan403/cloud-config.git
          username:
          password:
          search-paths: config-project
          search-paths: config-uc
          force-pull: true